{% set name = "circuitq" %}
{% set version = "1.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 7c87ae3099b58e957c35ab77c294304fd3b356e2e470d2bbb356d357adc83ea8

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6

  run:
    - networkx
    - numpy
    - python >=3.6
    - scipy
    - sympy

test:
  imports:
    - circuitq

about:
  home: "https://github.com/PhilippAumann/circuitq"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Automated design of superconducting qubits"
  doc_url: "https://circuitq.readthedocs.io/en/latest/"
  dev_url: "https://github.com/PhilippAumann/circuitq"

extra:
  recipe-maintainers:
    - PhilippAumann
